controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_login
        permanent: false
        app_logout:
            path: /logout
            methods: GET